language: rust
sudo: required
dist: trusty

cache:
  cargo: true
  apt: true

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly-2019-11-07
  allow_failures:
    - rust: nightly-2019-11-07

env:
  global:
    - RUSTFLAGS="-C link-dead-code"
    - OPENSSL_VERSION=openssl-1.0.2

before_install:
  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly-2019-11-07" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --version 0.6.11 cargo-tarpaulin
  fi

# Add clippy
before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly-2019-11-07" ]]; then
    cargo clean
    cargo test --all --all-features -- --nocapture
    fi

after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly-2019-11-07" ]]; then
    taskset -c 0 cargo tarpaulin --all --all-features --out Xml
    echo "Uploaded code coverage"
    bash <(curl -s https://codecov.io/bash)
    fi
