[package]
name = "ntex-router"
version = "2.1.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Path router"
keywords = ["ntex"]
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-router/"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.97"

[lib]
name = "ntex_router"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
ntex-bytes = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
urly = { workspace = true }

[dev-dependencies]
serde_derive = { workspace = true }
