name: API docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2.8.2
        with:
          cache-on-failure: true

      - name: Build docs
        run:
          cargo doc --no-deps --workspace --no-default-features --features="ntex/tokio,ntex/openssl,ntex/rustls,ntex/compress,ntex/cookie,ntex/ws,ntex-tls/rustls-ring"

      - name: Add index redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=ntex/index.html">' > target/doc/index.html
          rm -f target/doc/.lock

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: target/doc

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
